[tool.poetry]
name = "ua-generic-rest-api"
version = "2.1.0"
description = "Provides basic REST API implementation for GET, PUT, POST, and DELETE."
authors = ["Your Name <you@example.com>"]
readme = "README.md"
license = "MIT"
packages = [{ include = "ua_generic_rest_api" }]

[tool.poetry.dependencies]
python = "^3.14"
requests = "^2.32"

[tool.poetry.group.dev.dependencies]
responses = "^0.25"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"